theme: jekyll-theme-slate
## Welcome to the github page of Devvveci

You can use the [editor on Github](https://github.com/Devvveci/NewGitTest/edit/master/index.md) to maintain and preview the content of your website in markdown files.

Whenever you commit to this repository, Github Pages will run [Devvveci]<!-- ... --> to rebuild pages in your site, from the content in your markdown files. 

## Markdown

Markdown is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for 

```markdown
Syntax highlighted code block

# Header 1
## Header 2
### Header 3

- Bulleted
- List
